# WEB SCRAPING – ASSIGNMENT 2 
# Answer Sheet

In [ ]:
!pip install selenium 
import selenium
from selenium import webdriver
import pandas as pd
from selenium.webdriver.common.by import By
import warnings
warnings.filterwarnings('ignore')
import time

Note : While Connecting to the automated web driver, please mention the driver path

# Q.1. python program to scrape data for “Data Analyst” Job position in “Bangalore” location,

In [ ]:
#Calling the automated chrome driver
driver = webdriver.Chrome(r'C:\Users\Vinit\Downloads\chromedriver.exe')

#URL to be web scrape

url = 'https://www.naukri.com/'
driver.get(url)


#Entering “Data Analyst” in “Skill, Designations, Companies” field

search_job = driver.find_element(By.XPATH,'/html/body/div[1]/div[6]/div/div/div[1]/div/div/div/input')
search_job.send_keys('Data Analyst')

#entering “Bangalore” in “enter the location” field

search_locn = driver.find_element(By.XPATH,'/html/body/div[1]/div[6]/div/div/div[5]/div/div/div/input')
search_locn.send_keys('Bangalore')

#clicking the search button
search_button = driver.find_element(By.CLASS_NAME,'qsbSubmit')
search_button.click()

In [ ]:
def get_Data_Analyst_jobs_details():
    #scrape first 10 jobs title
    job_titles = []
    title_tag = driver.find_elements(By.XPATH,"//a[@class='title fw500 ellipsis']")

    for i in title_tag[:10]:
        job_titles.append(i.text)

    #scrape first 10 Company names
    company_name = []
    company_tag = driver.find_elements(By.XPATH,"//a[@class='subTitle ellipsis fleft']")

    for i in company_tag[:10]:
        company_name.append(i.text)

    #scrape first 10 required experience
    experience = []
    exp_tag = driver.find_elements(By.XPATH,"//span[@class='ellipsis fleft fs12 lh16 expwdth']")

    for i in exp_tag[:10]:
        experience.append(i.text)    

    #scrape first 10 jobs locations   
    Location = []
    loc_tag = driver.find_elements(By.XPATH,"//span[@class='ellipsis fleft fs12 lh16 locWdth']")

    for i in loc_tag[:10]:
        Location.append(i.text)

    #Creating dictionary of all titles, location, experience, company names with scaped data

    dict = {'Job Title':job_titles,'Job Location': Location, 'Comapany Name':company_name, 'Expereince Required': experience,}

    #Converting it into pandas dataframe
    df = pd.DataFrame(dict)
    
    
    driver.close()
    
    return df.head(10)

### Answer
- Top 10 job details for r “Data Analyst” Job position in “Bangalore”

In [ ]:
get_Data_Analyst_jobs_details()

# Q.2.python program to scrape data for “Data Scientist” Job position in “Bangalore” location

In [ ]:
#Calling the automated chrome driver
driver = webdriver.Chrome(r'C:\Users\Vinit\Downloads\chromedriver.exe')

#URL to be web scrape

url = 'https://www.naukri.com/'
driver.get(url)


#Entering “Data Analyst” in “Skill, Designations, Companies” field

search_job = driver.find_element(By.XPATH,'/html/body/div[1]/div[6]/div/div/div[1]/div/div/div/input')
search_job.send_keys('Data Scientist')

#entering “Bangalore” in “enter the location” field

search_locn = driver.find_element(By.XPATH,'/html/body/div[1]/div[6]/div/div/div[5]/div/div/div/input')
search_locn.send_keys('Bangalore')

#clicking the search button
search_button = driver.find_element(By.CLASS_NAME,'qsbSubmit')
search_button.click()

In [ ]:
def get_Data_Scientist_jobs_details():
    #scrape first 10 jobs title
    job_titles = []
    title_tag = driver.find_elements(By.XPATH,"//a[@class='title fw500 ellipsis']")

    for i in title_tag[:10]:
        job_titles.append(i.text)

    #scrape first 10 Company names
    company_name = []
    company_tag = driver.find_elements(By.XPATH,"//a[@class='subTitle ellipsis fleft']")

    for i in company_tag[:10]:
        company_name.append(i.text) 

    #scrape first 10 jobs locations   
    Location = []
    loc_tag = driver.find_elements(By.XPATH,"//span[@class='ellipsis fleft fs12 lh16 locWdth']")

    for i in loc_tag[:10]:
        Location.append(i.text)

    #Creating dictionary of all titles, location, experience, company names with scaped data

    dict = {'Job Title':job_titles,'Job Location': Location, 'Comapany Name':company_name,}

    #Converting it into pandas dataframe
    df = pd.DataFrame(dict)
    driver.close()
    return df.head(10)

In [ ]:
get_Data_Scientist_jobs_details()

# Q.3. Python program to use the location and salary filter, to get top 10 jobs of “Data Scientist”  at 'Delhi NCR'

In [ ]:
#URL to be web scrape

url = 'https://www.naukri.com/'
driver.get(url)


#Entering “Data Analyst” in “Skill, Designations, Companies” field

search_job = driver.find_element(By.XPATH,'/html/body/div[1]/div[6]/div/div/div[1]/div/div/div/input')
search_job.send_keys('Data Scientist')


#clicking the search button
search_button = driver.find_element(By.CLASS_NAME,'qsbSubmit')
search_button.click()


locat_button = driver.find_element(By.XPATH,"//span[@class='ellipsis fleft' and @title='Delhi / NCR']")
locat_button.click()

# Q.4.Scrape data of first 100 sunglasses listings on flipkart.com

In [ ]:
#Calling the automated chrome driver
driver = webdriver.Chrome(r'C:\Users\Vinit\Downloads\chromedriver.exe')


#URL to be web scrape

url = 'https://www.flipkart.com/'
driver.get(url)


cross_button = driver.find_element(By.XPATH,'/html/body/div[2]/div/div/button')
cross_button.click()

#Search sunglasses product
search_product = driver.find_element(By.XPATH,"//input[@class='_3704LK']")
search_product.send_keys('sunglasses')

#clicking the search button
search_button = driver.find_element(By.CLASS_NAME,'L0Z3Pu')
search_button.click()


#Declaring lists for the data to be extracted
Product_titles = []
Product_brand = []
Product_price= []

def get_product_titles():  
    title_tag = driver.find_elements(By.XPATH,"//a[contains(@class,'IRpwTa')]")

    for i in title_tag:
        Product_titles.append(i.text)
    
def get_product_brand():
    brand_tag = driver.find_elements(By.XPATH,"//div[contains(@class,'_2WkVRV')]")

    for i in brand_tag:
        Product_brand.append(i.text)
        
def get_product_price():    
    price_tag = driver.find_elements(By.XPATH,"//div[@class='_30jeq3']")

    for i in price_tag:
        Product_price.append(i.text)

In [ ]:
#Creating list of href of next page links
nxt_page=[]
next_tag =driver.find_elements(By.XPATH,"//a[contains(@class,'ge-49M')]")
for page in next_tag:
    p1 = page.get_attribute('href')
    #print(p1)
    nxt_page.append(p1)

In [ ]:
#Extracting the required data from first three pages
for i in range(3):
    driver.get(nxt_page[i])
    print('Extracting page',i+1)
    get_product_titles()
    get_product_brand()
    get_product_price()
    
    
    
#Creating dictionary from the extracted data as list form

dict = {'Product Name':Product_titles[:100],'Product Brand':Product_brand[:100],'Product Price':Product_price[:100]}
dict
df = pd.DataFrame(dict)

driver.close()

df

# Q5: Scrape 100 reviews data from flipkart.com for iphone11 phone

In [ ]:
url = 'https://www.flipkart.com/apple-iphone-11-black-64-gb/p/itm4e5041ba101fd?pid=MOBFWQ6BXGJCEYNY&lid=LSTMOBFWQ6BXGJCEYNYZXSHRJ&marketplace=FLIPKART&q=iphone+11+black+64gb&store=tyy%2F4io&srno=s_1_1&otracker=search&otracker1=search&fm=Search&iid=179577e7-ebfd-4f68-9573-dc237ea37ee1.MOBFWQ6BXGJCEYNY.SEARCH&ppt=sp&ppn=sp&ssid=avfi6gg60g0000001667671814002&qH=c8bcf01bd7ceddcb'
driver.get(url)


all_review = driver.find_element(By.XPATH,"//div[@class='_3UAT2v _16PBlm']")
all_review.click()

star_list=[]
review_list=[]
summary_list = []

In [ ]:
def get_review_titles():  
    review_tag = driver.find_elements(By.XPATH,"//p[@class='_2-N8zT']")

    for i in review_tag:
        review_list.append(i.text)
    
def get_review_summary():
    summary_tag = driver.find_elements(By.XPATH,"//div[@class='t-ZTKy']")
    for i in summary_tag:
        summary_list.append(i.text)
        
def get_rating_stars():    
    star_tags = driver.find_elements(By.XPATH,"//div[contains(@class,'_3LWZlK ')]")

    for i in star_tags:
        star_list.append(i.text)

In [ ]:
nxt_page=[]
next_tag =driver.find_elements(By.XPATH,"//a[contains(@class,'ge-49M')]")
for page in next_tag:
    p1 = page.get_attribute('href')
    #print(p1)
    nxt_page.append(p1)

In [ ]:
#Extracting the required data from first three pages
for a in range(0,10):
    driver.get(nxt_page[a])
    print('Extracting page',a+1)
    get_review_titles()
    get_review_summary()
    get_rating_stars()
    
    

driver.close()
#Creating dictionary from the extracted data as list form

dict = {'Review':review_list,'Summary':summary_list,'Raring Stars':star_list}

dict
df = pd.DataFrame(dict)



df

# Q6: Scrape data for first 100 sneakers you find when you visit flipkart.com and search for “sneakers” in the search field.

In [ ]:
#Calling the automated chrome driver
driver = webdriver.Chrome(r'C:\Users\Vinit\Downloads\chromedriver.exe')


#URL to be web scrape

url = 'https://www.flipkart.com/'
driver.get(url)


cross_button = driver.find_element(By.XPATH,'/html/body/div[2]/div/div/button')
cross_button.click()

#Search sunglasses product
search_product = driver.find_element(By.XPATH,"//input[@class='_3704LK']")
search_product.send_keys('sneakers')

#clicking the search button
search_button = driver.find_element(By.CLASS_NAME,'L0Z3Pu')
search_button.click()


#Declaring lists for the data to be extracted
Product_titles = []
Product_brand = []
Product_price= []

def get_product_titles():  
    title_tag = driver.find_elements(By.XPATH,"//a[contains(@class,'IRpwTa')]")

    for i in title_tag:
        Product_titles.append(i.text)
    
def get_product_brand():
    brand_tag = driver.find_elements(By.XPATH,"//div[contains(@class,'_2WkVRV')]")

    for i in brand_tag:
        Product_brand.append(i.text)
        
def get_product_price():    
    price_tag = driver.find_elements(By.XPATH,"//div[@class='_30jeq3']")

    for i in price_tag:
        Product_price.append(i.text)

In [ ]:
#Creating list of href of next page links
nxt_page=[]
next_tag =driver.find_elements(By.XPATH,"//a[contains(@class,'ge-49M')]")
for page in next_tag:
    p1 = page.get_attribute('href')
    #print(p1)
    nxt_page.append(p1)

In [ ]:
#Extracting the required data from first three pages
for i in range(3):
    driver.get(nxt_page[i])
    print('Extracting page',i+1)
    get_product_titles()
    get_product_brand()
    get_product_price()
    
    
    
#Creating dictionary from the extracted data as list form

dict = {'Product Description':Product_titles[:100],'Product Brand':Product_brand[:100],'Product Price':Product_price[:100]}
dict
df = pd.DataFrame(dict)

driver.close()

df

# Q.7.: Go to the link - https://www.myntra.com/shoes Set second Price filter and Color filter to “Black” ,scrape First 100 shoes data you get

In [ ]:
#Calling the automated chrome driver
driver = webdriver.Chrome(r'C:\Users\Vinit\Downloads\chromedriver.exe')

#URL to be web scrape

url = 'https://www.myntra.com/shoes'
driver.get(url)

black = driver.find_element(By.XPATH,"(//label[@class='common-customCheckbox'])[1]")
black.click()

price = driver.find_element(By.XPATH,"(//label[@class='common-customCheckbox vertical-filters-label'])[9]")
price.click()


Product_titles = []
Product_brand = []
Product_price= []

def get_product_titles():  
    title_tag = driver.find_elements(By.XPATH,"//h4[@class='product-product']")

    for i in title_tag:
        Product_titles.append(i.text)
    
def get_product_brand():
    brand_tag = driver.find_elements(By.XPATH,"//h3[@class='product-brand']")

    for i in brand_tag:
        Product_brand.append(i.text)
        
def get_product_price():    
    price_tag = driver.find_elements(By.XPATH,"//div[@class='product-price']")

    for i in price_tag:
        Product_price.append(i.text)

In [ ]:
#First page info
get_product_titles()
get_product_brand()
get_product_price()

#Clicking next button for 2nd page
next_tag =driver.find_element(By.XPATH,"//a[contains(text(),'2')]")
next_tag.click()

#seconf page info
get_product_titles()
get_product_brand()
get_product_price()

driver.close()

In [ ]:

dict = {'Product Name':Product_titles[:100],'Product Brand':Product_brand[:100],'Product Price':Product_price[:100]}
dict
df = pd.DataFrame(dict) 

df

# Q.8. scrape first 10 laptops data from amazon.com

In [109]:
#Calling the automated chrome driver
driver = webdriver.Chrome(r'C:\Users\Vinit\Downloads\chromedriver.exe')


#URL to be web scrape

url = 'https://www.amazon.in/'
driver.get(url)

#Search sunglasses product
search_product = driver.find_element(By.XPATH,"//input[@id='twotabsearchtextbox']")
search_product.send_keys('Laptop')

#clicking the search button
search_button = driver.find_element(By.XPATH,"//input[@id='nav-search-submit-button']")
search_button.click()

cpu = driver.find_element(By.XPATH,"//span[contains(text(),'Intel Core i7')]")
cpu.click()

Product_titles = []
Product_rating = []
Product_price= []

 #Extracting the laptop name 
title_tag = driver.find_elements(By.XPATH,"//span[@class='a-size-medium a-color-base a-text-normal']")

for i in title_tag:
    Product_titles.append(i.text)
    
 #Extracting the price

price_tag = driver.find_elements(By.XPATH,"//span[@class='a-price-whole']")

for i in price_tag:
    Product_price.append(i.text)
    
 #Extracting the rating

rating_tag = driver.find_elements(By.XPATH,"//span[contains(@aria-label,'of 5 stars')]")

for i in range(15):
    Product_rating.append(rating_tag[i].get_attribute('aria-label'))
    
driver.close()

In [111]:
#Forming dataframe from extracted dictionary

dict = {'Laptop Name':Product_titles[:10],'Ratings':Product_rating[:10],'Price':Product_price[:10]}
dict
df = pd.DataFrame(dict) 

df

,Laptop Name,Ratings,Price
0,Lenovo IdeaPad Slim 5 12th Gen Intel Core i7 1...,4.3 out of 5 stars,"83,990"
1,HP Pavilion x360 11th Gen Intel Core i7 14 inc...,4.6 out of 5 stars,"80,490"
2,(Renewed) HP ProBook 430 G3 6th Gen Intel Core...,3.5 out of 5 stars,"25,895"
3,HP Victus 12th Gen Intel Core i7 15.6 inch(39....,3.6 out of 5 stars,"97,500"
4,Lenovo ThinkBook 15 Intel 11th Gen Core i7 15....,5.0 out of 5 stars,"77,990"
5,(Renewed) HP Workstation Zbook Intel Core i7-4...,4.0 out of 5 stars,"21,990"
6,"(Renewed) ASUS TUF Gaming F15 (2022), 15.6-inc...",2.8 out of 5 stars,"1,02,240"
7,(Renewed) HP Workstation Zbook Intel Core i7-4...,3.2 out of 5 stars,"25,990"
8,(Renewed) HP Workstation Zbook Intel Core i7-4...,4.6 out of 5 stars,"41,990"
9,Lenovo ThinkBook 15 Intel 12th Gen Core i7 15....,4.0 out of 5 stars,"86,490"

# Q.9.Write a python program to scrape data for Top 1000 Quotes of All Time.

In [ ]:
#Calling the automated chrome driver
driver = webdriver.Chrome(r'C:\Users\Vinit\Downloads\chromedriver.exe')


#URL to be web scrape

url = 'https://www.azquotes.com/'
driver.get(url)

#clicking the search button
top_button = driver.find_element(By.XPATH,"/html/body/div[1]/div[1]/div[1]/div/div[3]/ul/li[5]/a")
top_button.click()

#Declaring the lists
Quote_titles = []
Quote_Author = []
Quote_type = []

#Defining the XPATH
title_tag = driver.find_elements(By.XPATH,"//a[@class='title']")
Author_tag = driver.find_elements(By.XPATH,"//div[@class='author']")
type_tag = driver.find_elements(By.XPATH,"//div[@class='tags']")
next_tag =driver.find_element(By.XPATH,"//li[@class='next']")


#Extracting the information on each pages using loop
for p in range(10):
    print('Ectracting page no.',p+1)
    
    title_tag = driver.find_elements(By.XPATH,"//a[@class='title']")
    for i in title_tag:
        Quote_titles.append(i.text)
    
    Author_tag = driver.find_elements(By.XPATH,"//div[@class='author']")    
    for i in Author_tag:
        Quote_Author.append(i.text)
    
    type_tag = driver.find_elements(By.XPATH,"//div[@class='tags']")    
    for i in type_tag:
        Quote_type.append(i.text)
        
    if p<9:
        next_tag =driver.find_element(By.XPATH,"//li[@class='next']")
        next_tag.click()  
    else:
        print('Top 1000 quotes Extracted')
driver.close()

In [113]:
#Forming dataframe from extracted dictionary
dict = {'Quote':Quote_titles,'Author':Quote_Author,'Type':Quote_type}
dict
df = pd.DataFrame(dict) 

df

,Quote,Author,Type
0,The essence of strategy is choosing what not t...,Michael Porter,"Essence, Deep Thought, Transcendentalism"
1,One cannot and must not try to erase the past ...,Golda Meir,"Inspiration, Past, Trying"
2,Patriotism means to stand by the country. It d...,Theodore Roosevelt,"Country, Peace, War"
3,Death is something inevitable. When a man has ...,Nelson Mandela,"Inspirational, Motivational, Death"
4,You have to love a nation that celebrates its ...,Erma Bombeck,"4th Of July, Food, Patriotic"
5,Be more concerned with your character than you...,John Wooden,"Inspirational, Success, Basketball"
6,Weak people revenge. Strong people forgive. In...,Albert Einstein,"Strong, Revenge, Intelligent"
7,A mind is like a parachute. It doesn't work if...,Frank Zappa,"Inspirational, Teacher, Religious"
8,Never be afraid to raise your voice for honest...,William Faulkner,"Truth, Honesty, Lying"
9,There are three kinds of men. The one that lea...,Will Rogers,"Funny, Reading, Learning"
10,"A strong nation, like a strong person, can aff...",Jimmy Carter,"Strong, Thoughtful, Compassion"
11,The difference between stupidity and genius is...,Albert Einstein,"Love, Funny, Life"
12,We the people are the rightful masters of both...,Abraham Lincoln,"Freedom, Men, Democracies Have"
13,"With or without religion, you would have good ...",Steven Weinberg,"God, Religious, Atheist"
14,Human kindness has never weakened the stamina ...,Franklin D. Roosevelt,"Respect, Kindness, Character"
15,A person who never made a mistake never tried ...,Albert Einstein,"Inspirational, Motivational, Change"
16,"My mission in life is not merely to survive, b...",Maya Angelou,"Inspirational, Life, Inspiring"
17,"Life is short, Break the Rules. Forgive quickl...",Mark Twain,"Love, Inspirational, Life"
18,This country will not be a good place for any ...,Theodore Roosevelt,"Inspiring, Country, 4th Of July"
19,"In a world filled with hate, we must still dar...",Michael Jackson,"Inspirational, Dream, Hate"
20,Darkness cannot drive out darkness; only light...,"Martin Luther King, Jr.","Love, Inspirational, Life"
21,To be a Christian means to forgive the inexcus...,C. S. Lewis,"Forgiveness, God, Christian"
22,A man who is good enough to shed his blood for...,Theodore Roosevelt,"Country, Men, Squares"
23,Kindness is the language which the deaf can he...,Mark Twain,"Inspirational, Relationship, Positive"
24,Most folks are as happy as they make up their ...,Abraham Lincoln,"Inspirational, Motivational, Positive"
25,A happy marriage is the union of two good forg...,Ruth Graham,"Love, Friendship, Relationship"
26,I believe in Christianity as I believe that th...,C. S. Lewis,"Faith, God, Christian"
27,"Politics is the art of looking for trouble, fi...",Groucho Marx,"Art, Freedom, Political Will"
28,I believe in everything until it's disproved. ...,John Lennon,"Inspirational, Life, Faith"
29,"At the end of your life, you will never regret...",Barbara Bush,"Inspirational, Life, Meaningful"
...,...,...,...
970,"It is best to act with confidence, no matter h...",Lillian Hellman,"Confidence, Littles, Matter"
971,People usually consider walking on water or in...,Nhat Hanh,"Motivational, Buddhist, Children"
972,Freedom means the opportunity to be what we ne...,Daniel J. Boorstin,"Mean, Opportunity, Nerd"
973,"For it was not into my ear you whispered, but ...",Judy Garland,"Love, Funny, Romantic"
974,"I will love the light for it shows me the way,...",Og Mandino,"Inspirational, Positive, Stars"
975,"If you run, you are a runner. It doesn't matte...",John Bingham,"Running, Years, Tests"
976,The deepest principle in human nature is the c...,William James,"Inspirational, Motivational, Relationship"
977,The world is a dangerous place to live; not be...,Albert Einstein,"Peace, Integrity, Patriotic"
978,Forgiveness says you are given another chance ...,Desmond Tutu,"Inspiring, Forgiveness, New Beginnings"
979,About all you can do in life is be who you are...,Rita Mae Brown,"Love, Life, Being Yourself"
980,"To find out what one is fitted to do, and to s...",John Dewey,"Happiness, Work, Opportunity"
981,What is success? I think it is a mixture of ha...,Margaret Thatcher,"Motivational, Success, Work"
982,The past has no power over the present moment.,Eckhart Tolle,"Positive, Wisdom, Philosophical"
983,"Do not let your fire go out, spark by irreplac...",Ayn Rand,"Inspirational, Life, Motivational"
984,No person was ever honored for what he receive...,Calvin Coolidge,"Life, Leadership, Motivational Sports"
985,"Wherever you are, and whatever you do, be in l...",Rumi,"Spiritual, Sufi, Wherever You Are"
986,Love yourself-accept yourself-forgive yourself...,Leo Buscaglia,"Love, Confidence, Forgiving"
987,Whenever you find yourself on the side of the ...,Mark Twain,"Inspirational, Motivational, Change"
988,And those who were seen dancing were thought t...,Friedrich Nietzsche,"Inspirational, Life, Music"
989,I love things that age well - things that don'...,Giorgio Armani,"Artist, Age, Example"
990,Better be wise by the misfortunes of others th...,Aesop,"Inspirational, Motivational, Wise"
991,"The person, be it gentleman or lady, who has n...",Jane Austen,"Inspirational, Funny, Stupid"
992,Curiosity is one of the most permanent and cer...,Samuel Johnson,"Education, Curiosity, Genius"
993,Leaders must be close enough to relate to othe...,John C. Maxwell,"Motivational, Inspiring, Leadership"
994,"The opposite of love is not hate, it's indiffe...",Elie Wiesel,"Love, Inspirational, Life"
995,Regret for the things we did can be tempered b...,Sydney J. Harris,"Love, Inspirational, Motivational"
996,America... just a nation of two hundred millio...,Hunter S. Thompson,"Gun, Two, Qualms About"
997,For every disciplined effort there is a multip...,Jim Rohn,"Inspirational, Greatness, Best Effort"
998,"The spiritual journey is individual, highly pe...",Ram Dass,"Spiritual, Truth, Yoga"
999,"No matter how plain a woman may be, if truth a...",Eleanor Roosevelt,"Beauty, Beautiful, Truth"

# Q10: Write s python program to display list of respected former Prime Ministers of India(i.e. Name, Born-Dead,Term of office, Remarks) from https://www.jagranjosh.com/.

In [ ]:
#Calling the automated chrome driver
driver = webdriver.Chrome(r'C:\Users\Vinit\Downloads\chromedriver.exe')


#URL to be web scrape

url = 'https://www.jagranjosh.com/'
driver.get(url)

#clicking the gk button
gk_button = driver.find_element(By.XPATH,"/html/body/div/div[1]/div/div[1]/div/div[6]/div/div[1]/header/div[3]/ul/li[9]/a")
gk_button.click()

#Clicking the prime minister link
primeminister_button = driver.find_element(By.XPATH,"/html/body/div[1]/div/div/div[2]/div/div[10]/div/div/ul/li[2]/a")
primeminister_button.click()

#DEclaring the lists
Names = []
Born_dead = []
Office_tenure = []
Remarks = []

#DEfining the XPATH
name_tag = driver.find_elements(By.XPATH,"//td[contains(@style,'width: 150px')]")
born_dead_tag = driver.find_elements(By.XPATH,"//td[contains(@style,'width: 105px')]")
Office_tag = driver.find_elements(By.XPATH,"//td[contains(@style,'width: 256px')]")
remark_tag = driver.find_elements(By.XPATH,"//td[contains(@style,'width: 145px')]")

#Extracting data
for i in name_tag:
        Names.append(i.text)
for i in born_dead_tag:
        Born_dead.append(i.text)
for i in Office_tag:
        Office_tenure.append(i.text)
for i in remark_tag:
        Remarks.append(i.text)
        
driver.close()
        
#Creating dictionary and then, dataframe from dictionary

dict = {'Name':Names,'Born-Dead':Born_dead,'Office Tenure':Office_tenure,'Remarks':Remarks}
df = pd.DataFrame(dict) 
df

# Q11: Write s python program to display list of 50 Most expensive cars in the world (i.e. Company name, Model name and Price) from https://www.motor1.com/

In [114]:
#Calling the automated chrome driver
driver = webdriver.Chrome(r'C:\Users\Vinit\Downloads\chromedriver.exe')


#URL to be web scrape

url = 'https://www.motor1.com/'
driver.get(url)

#clicking the search button
menu_button = driver.find_element(By.XPATH,"/html/body/div[2]/div[2]/div/div/div[1]/div")
menu_button.click()

#Heading towards list
list_button = driver.find_element(By.XPATH,"//body/div[3]/div[1]/div[3]/ul[1]/li[4]/a[1]")
l1=list_button.get_attribute('href')
driver.get(l1)

#Redirecting towrds top 50 cars
topic_tag = driver.find_element(By.XPATH,'/html/body/div[2]/div[9]/div[1]/div[1]/div/div/div[1]/div/div[1]/h3/a')
p1=topic_tag.get_attribute('href')
driver.get(p1)

#Initiating lists
Titles = []
company_name = []
price = []
car =[]
final_price = []

#Extracting car model and company together
title_tag = driver.find_elements(By.XPATH,"//h3[@class='subheader']")
for i in title_tag:
    Titles.append(i.text.split())
    
#Seperating company name
for i in Titles:
    company_name.append(i[0])

#Seperating car model
for i in Titles:
    car.append(i[1])

#Extracting prices for cars    
price_tag = driver.find_elements(By.XPATH,"//strong[contains(text(),'$')]")
for i in price_tag:
    price.append(i.text)

driver.close()
#creating a dictionary of data collected in form of lists
dict = {'Model':car[:50],'Brand':company_name[:50],'Price':price[:50]}

#Creating dataframe from dictionary
df = pd.DataFrame(dict) 
df

         Model             Brand                        Price
0          GTE             Drako          Price: $1.2 Million
1       Tomaso                De          Price: $1.3 Million
2    LaFerrari           Ferrari          Price: $1.4 Million
3       Huayra            Pagani          Price: $1.4 Million
4         Elva           McLaren          Price: $1.7 Million
5          21C           Czinger          Price: $1.7 Million
6        Monza           Ferrari          Price: $1.7 Million
7       Murray            Gordon          Price: $1.7 Million
8       Gemera        Koenigsegg          Price: $1.7 Million
9        TSR-S             Zenvo          Price: $1.7 Million
10       Venom         Hennessey          Price: $1.8 Million
11     Bacalar           Bentley          Price: $1.9 Million
12       Suiza           Hispano          Price: $1.9 Million
13    Mulliner           Bentley          Price: $2.0 Million
14     Vayanne              Deus          Price: $2.0 Million
15     Tuatara               SSC         Price: $2.0 Million*
16       Evija             Lotus          Price: $2.1 Million
17      Martin             Aston          Price: $2.3 Million
18         D12            Delage          Price: $2.3 Million
19   Speedtail           McLaren          Price: $2.3 Million
20      Nevera             Rimac          Price: $2.4 Million
21      Utopia            Pagani          Price: $2.5 Million
22    Battista       Pininfarina          Price: $2.5 Million
23         FXX           Ferrari          Price: $2.6 Million
24      Murray            Gordon          Price: $2.6 Million
25    Countach       Lamborghini          Price: $2.6 Million
26     Project      Mercedes-AMG          Price: $2.7 Million
27      Martin             Aston          Price: $3.0 Million
28       Venom         Hennessey                 $3.0 Million
29       Jesko        Koenigsegg          Price: $3.0 Million
30      Martin             Aston          Price: $3.2 Million
31      Motors                 W          Price: $3.4 Million
32       Solus           McLaren                 $3.5 Million
33      Huayra            Pagani          Price: $3.5 Million
34      Chiron           Bugatti          Price: $3.6 Million
35        Sian       Lamborghini          Price: $3.6 million
36       CC850        Koenigsegg          Price: $3.7 Million
37      Chiron           Bugatti          Price: $3.9 Million
38      Veneno       Lamborghini          Price: $4.5 Million
39      Bolide           Bugatti          Price: $4.7 Million
40     Mistral           Bugatti          Price: $5.0 Million
41      Huayra            Pagani          Price: $5.4 Million
42        Divo           Bugatti          Price: $5.8 Million
43  Automotive                SP          Price: $6.4 Million
44   Codalunga            Pagani          Price: $7.4 Million
45     Exelero  Mercedes-Maybach          Price: $8.0 Million
46  Centodieci           Bugatti          Price: $9.0 Million
47    Sweptail       Rolls-Royce         Price: $12.8 Million
48          La           Bugatti         Price: $13.4 Million
49        Boat       Rolls-Royce  Price: $28.0 Million (est.)